/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServerSetupRouteImport } from './routes/server-setup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as ImportRouteImport } from './routes/import'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DeploysRouteImport } from './routes/deploys'
import { Route as CreateRouteImport } from './routes/create'
import { Route as ConnectorsRouteImport } from './routes/connectors'
import { Route as CodexRouteImport } from './routes/codex'
import { Route as CloudRouteImport } from './routes/cloud'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VersionsProjectIdRouteImport } from './routes/versions.$projectId'
import { Route as PublishProjectIdRouteImport } from './routes/publish.$projectId'
import { Route as PreviewProjectIdRouteImport } from './routes/preview.$projectId'
import { Route as BuilderProjectIdRouteImport } from './routes/builder.$projectId'
import { Route as ApiPublicBuildRunnerRouteImport } from './routes/api/public/build-runner'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerSetupRoute = ServerSetupRouteImport.update({
  id: '/server-setup',
  path: '/server-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploysRoute = DeploysRouteImport.update({
  id: '/deploys',
  path: '/deploys',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsRoute = ConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const CodexRoute = CodexRouteImport.update({
  id: '/codex',
  path: '/codex',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudRoute = CloudRouteImport.update({
  id: '/cloud',
  path: '/cloud',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VersionsProjectIdRoute = VersionsProjectIdRouteImport.update({
  id: '/versions/$projectId',
  path: '/versions/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishProjectIdRoute = PublishProjectIdRouteImport.update({
  id: '/publish/$projectId',
  path: '/publish/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewProjectIdRoute = PreviewProjectIdRouteImport.update({
  id: '/preview/$projectId',
  path: '/preview/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderProjectIdRoute = BuilderProjectIdRouteImport.update({
  id: '/builder/$projectId',
  path: '/builder/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBuildRunnerRoute = ApiPublicBuildRunnerRouteImport.update({
  id: '/api/public/build-runner',
  path: '/api/public/build-runner',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/cloud': typeof CloudRoute
  '/codex': typeof CodexRoute
  '/connectors': typeof ConnectorsRoute
  '/create': typeof CreateRoute
  '/deploys': typeof DeploysRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/health': typeof HealthRoute
  '/help': typeof HelpRoute
  '/import': typeof ImportRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/server-setup': typeof ServerSetupRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/team': typeof TeamRoute
  '/builder/$projectId': typeof BuilderProjectIdRoute
  '/preview/$projectId': typeof PreviewProjectIdRoute
  '/publish/$projectId': typeof PublishProjectIdRoute
  '/versions/$projectId': typeof VersionsProjectIdRoute
  '/api/public/build-runner': typeof ApiPublicBuildRunnerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/cloud': typeof CloudRoute
  '/codex': typeof CodexRoute
  '/connectors': typeof ConnectorsRoute
  '/create': typeof CreateRoute
  '/deploys': typeof DeploysRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/health': typeof HealthRoute
  '/help': typeof HelpRoute
  '/import': typeof ImportRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/server-setup': typeof ServerSetupRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/team': typeof TeamRoute
  '/builder/$projectId': typeof BuilderProjectIdRoute
  '/preview/$projectId': typeof PreviewProjectIdRoute
  '/publish/$projectId': typeof PublishProjectIdRoute
  '/versions/$projectId': typeof VersionsProjectIdRoute
  '/api/public/build-runner': typeof ApiPublicBuildRunnerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/cloud': typeof CloudRoute
  '/codex': typeof CodexRoute
  '/connectors': typeof ConnectorsRoute
  '/create': typeof CreateRoute
  '/deploys': typeof DeploysRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/health': typeof HealthRoute
  '/help': typeof HelpRoute
  '/import': typeof ImportRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/server-setup': typeof ServerSetupRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/team': typeof TeamRoute
  '/builder/$projectId': typeof BuilderProjectIdRoute
  '/preview/$projectId': typeof PreviewProjectIdRoute
  '/publish/$projectId': typeof PublishProjectIdRoute
  '/versions/$projectId': typeof VersionsProjectIdRoute
  '/api/public/build-runner': typeof ApiPublicBuildRunnerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/cloud'
    | '/codex'
    | '/connectors'
    | '/create'
    | '/deploys'
    | '/forgot-password'
    | '/health'
    | '/help'
    | '/import'
    | '/integrations'
    | '/login'
    | '/projects'
    | '/reset-password'
    | '/server-setup'
    | '/settings'
    | '/signup'
    | '/team'
    | '/builder/$projectId'
    | '/preview/$projectId'
    | '/publish/$projectId'
    | '/versions/$projectId'
    | '/api/public/build-runner'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/cloud'
    | '/codex'
    | '/connectors'
    | '/create'
    | '/deploys'
    | '/forgot-password'
    | '/health'
    | '/help'
    | '/import'
    | '/integrations'
    | '/login'
    | '/projects'
    | '/reset-password'
    | '/server-setup'
    | '/settings'
    | '/signup'
    | '/team'
    | '/builder/$projectId'
    | '/preview/$projectId'
    | '/publish/$projectId'
    | '/versions/$projectId'
    | '/api/public/build-runner'
  id:
    | '__root__'
    | '/'
    | '/billing'
    | '/cloud'
    | '/codex'
    | '/connectors'
    | '/create'
    | '/deploys'
    | '/forgot-password'
    | '/health'
    | '/help'
    | '/import'
    | '/integrations'
    | '/login'
    | '/projects'
    | '/reset-password'
    | '/server-setup'
    | '/settings'
    | '/signup'
    | '/team'
    | '/builder/$projectId'
    | '/preview/$projectId'
    | '/publish/$projectId'
    | '/versions/$projectId'
    | '/api/public/build-runner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillingRoute: typeof BillingRoute
  CloudRoute: typeof CloudRoute
  CodexRoute: typeof CodexRoute
  ConnectorsRoute: typeof ConnectorsRoute
  CreateRoute: typeof CreateRoute
  DeploysRoute: typeof DeploysRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HealthRoute: typeof HealthRoute
  HelpRoute: typeof HelpRoute
  ImportRoute: typeof ImportRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LoginRoute: typeof LoginRoute
  ProjectsRoute: typeof ProjectsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServerSetupRoute: typeof ServerSetupRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TeamRoute: typeof TeamRoute
  BuilderProjectIdRoute: typeof BuilderProjectIdRoute
  PreviewProjectIdRoute: typeof PreviewProjectIdRoute
  PublishProjectIdRoute: typeof PublishProjectIdRoute
  VersionsProjectIdRoute: typeof VersionsProjectIdRoute
  ApiPublicBuildRunnerRoute: typeof ApiPublicBuildRunnerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server-setup': {
      id: '/server-setup'
      path: '/server-setup'
      fullPath: '/server-setup'
      preLoaderRoute: typeof ServerSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deploys': {
      id: '/deploys'
      path: '/deploys'
      fullPath: '/deploys'
      preLoaderRoute: typeof DeploysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors': {
      id: '/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof ConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codex': {
      id: '/codex'
      path: '/codex'
      fullPath: '/codex'
      preLoaderRoute: typeof CodexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloud': {
      id: '/cloud'
      path: '/cloud'
      fullPath: '/cloud'
      preLoaderRoute: typeof CloudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/versions/$projectId': {
      id: '/versions/$projectId'
      path: '/versions/$projectId'
      fullPath: '/versions/$projectId'
      preLoaderRoute: typeof VersionsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publish/$projectId': {
      id: '/publish/$projectId'
      path: '/publish/$projectId'
      fullPath: '/publish/$projectId'
      preLoaderRoute: typeof PublishProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/$projectId': {
      id: '/preview/$projectId'
      path: '/preview/$projectId'
      fullPath: '/preview/$projectId'
      preLoaderRoute: typeof PreviewProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/$projectId': {
      id: '/builder/$projectId'
      path: '/builder/$projectId'
      fullPath: '/builder/$projectId'
      preLoaderRoute: typeof BuilderProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/build-runner': {
      id: '/api/public/build-runner'
      path: '/api/public/build-runner'
      fullPath: '/api/public/build-runner'
      preLoaderRoute: typeof ApiPublicBuildRunnerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillingRoute: BillingRoute,
  CloudRoute: CloudRoute,
  CodexRoute: CodexRoute,
  ConnectorsRoute: ConnectorsRoute,
  CreateRoute: CreateRoute,
  DeploysRoute: DeploysRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HealthRoute: HealthRoute,
  HelpRoute: HelpRoute,
  ImportRoute: ImportRoute,
  IntegrationsRoute: IntegrationsRoute,
  LoginRoute: LoginRoute,
  ProjectsRoute: ProjectsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServerSetupRoute: ServerSetupRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TeamRoute: TeamRoute,
  BuilderProjectIdRoute: BuilderProjectIdRoute,
  PreviewProjectIdRoute: PreviewProjectIdRoute,
  PublishProjectIdRoute: PublishProjectIdRoute,
  VersionsProjectIdRoute: VersionsProjectIdRoute,
  ApiPublicBuildRunnerRoute: ApiPublicBuildRunnerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
